

spring:
  # MySQL database for Spring Batch job repository
  datasource:
    url: jdbc:mysql://localhost:3306/batch_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: abc@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  batch:
    jdbc:
      initialize-schema: always

scheduler:
  fixed-rate: 5000000

kafka:
  bootstrap-servers: localhost:9092,localhost:9094
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    acks: all
    retries: 3
    batch-size: 16384
    linger-ms: 100
    compression-type: lz4
    max-in-flight-requests-per-connection: 5
    enable-idempotence: true
    retry-backoff-ms: 1000
  topics-source: inbound-symbol-source

logging:
  level:
    root: info
    org.trading.application.*: INFO

source:
  binance:
    url: https://api.binance.com/api/v3/ticker/bookTicker
    kline-url: https://api.binance.com/api/v3/klines
    ticker: https://api.binance.com/api/v3/ticker/
    depth: https://api.binance.com/api/v3/depth
    kline-white-list-symbol: BTCUSDT,ETHUSDT,SOLUSDT,ADAUSDT

  huobi:
    url: https://api.huobi.pro/market/tickers
server:
  port: 11080

  servlet:
    context-path: /api